<?php
/**
 * CardBrand
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect\Model;

/**
 * CardBrand Class Doc Comment
 *
 * @category    Class
 * @description Indicates a credit card&#39;s brand, such as &#x60;VISA&#x60;.
 * @package     SquareConnect
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CardBrand
{
    /**
     * Possible values of this enum
     */
    const OTHER_BRAND = 'OTHER_BRAND';
    const VISA = 'VISA';
    const MASTERCARD = 'MASTERCARD';
    const AMERICAN_EXPRESS = 'AMERICAN_EXPRESS';
    const DISCOVER = 'DISCOVER';
    const DISCOVER_DINERS = 'DISCOVER_DINERS';
    const JCB = 'JCB';
    const CHINA_UNIONPAY = 'CHINA_UNIONPAY';
    const SQUARE_GIFT_CARD = 'SQUARE_GIFT_CARD';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OTHER_BRAND,
            self::VISA,
            self::MASTERCARD,
            self::AMERICAN_EXPRESS,
            self::DISCOVER,
            self::DISCOVER_DINERS,
            self::JCB,
            self::CHINA_UNIONPAY,
            self::SQUARE_GIFT_CARD,
        ];
    }
}


