<?php
/**
 * CatalogDiscountType
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect\Model;

/**
 * CatalogDiscountType Class Doc Comment
 *
 * @category    Class
 * @description How to apply a [CatalogDiscount](#type-catalogdiscount) to a [CatalogItem](#type-catalogitem).
 * @package     SquareConnect
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CatalogDiscountType
{
    /**
     * Possible values of this enum
     */
    const FIXED_PERCENTAGE = 'FIXED_PERCENTAGE';
    const FIXED_AMOUNT = 'FIXED_AMOUNT';
    const VARIABLE_PERCENTAGE = 'VARIABLE_PERCENTAGE';
    const VARIABLE_AMOUNT = 'VARIABLE_AMOUNT';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FIXED_PERCENTAGE,
            self::FIXED_AMOUNT,
            self::VARIABLE_PERCENTAGE,
            self::VARIABLE_AMOUNT,
        ];
    }
}


