<?php
/**
 * CatalogObjectType
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect\Model;

/**
 * CatalogObjectType Class Doc Comment
 *
 * @category    Class
 * @description Possible kinds of [CatalogObject](#type-catalogobject)s returned from the Catalog, each contaning type-specific properties in the &#x60;*_data&#x60; field corresponding to the object type.
 * @package     SquareConnect
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CatalogObjectType
{
    /**
     * Possible values of this enum
     */
    const ITEM = 'ITEM';
    const CATEGORY = 'CATEGORY';
    const ITEM_VARIATION = 'ITEM_VARIATION';
    const TAX = 'TAX';
    const DISCOUNT = 'DISCOUNT';
    const MODIFIER_LIST = 'MODIFIER_LIST';
    const MODIFIER = 'MODIFIER';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ITEM,
            self::CATEGORY,
            self::ITEM_VARIATION,
            self::TAX,
            self::DISCOUNT,
            self::MODIFIER_LIST,
            self::MODIFIER,
        ];
    }
}


