<?php
/**
 * CatalogQueryRange
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect\Model;

use \ArrayAccess;

/**
 * CatalogQueryRange Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     SquareConnect
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CatalogQueryRange implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'CatalogQueryRange';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'attribute_name' => 'string',
        'attribute_min_value' => 'int',
        'attribute_max_value' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'attribute_name' => null,
        'attribute_min_value' => 'int64',
        'attribute_max_value' => 'int64'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'attribute_name' => 'attribute_name',
        'attribute_min_value' => 'attribute_min_value',
        'attribute_max_value' => 'attribute_max_value'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'attribute_name' => 'setAttributeName',
        'attribute_min_value' => 'setAttributeMinValue',
        'attribute_max_value' => 'setAttributeMaxValue'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'attribute_name' => 'getAttributeName',
        'attribute_min_value' => 'getAttributeMinValue',
        'attribute_max_value' => 'getAttributeMaxValue'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['attribute_name'] = isset($data['attribute_name']) ? $data['attribute_name'] : null;
        $this->container['attribute_min_value'] = isset($data['attribute_min_value']) ? $data['attribute_min_value'] : null;
        $this->container['attribute_max_value'] = isset($data['attribute_max_value']) ? $data['attribute_max_value'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['attribute_name'] === null) {
            $invalid_properties[] = "'attribute_name' can't be null";
        }
        if ((strlen($this->container['attribute_name']) < 1)) {
            $invalid_properties[] = "invalid value for 'attribute_name', the character length must be bigger than or equal to 1.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['attribute_name'] === null) {
            return false;
        }
        if (strlen($this->container['attribute_name']) < 1) {
            return false;
        }
        return true;
    }


    /**
     * Gets attribute_name
     * @return string
     */
    public function getAttributeName()
    {
        return $this->container['attribute_name'];
    }

    /**
     * Sets attribute_name
     * @param string $attribute_name The name of the attribute to be searched.
     * @return $this
     */
    public function setAttributeName($attribute_name)
    {

        if ((strlen($attribute_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $attribute_name when calling CatalogQueryRange., must be bigger than or equal to 1.');
        }

        $this->container['attribute_name'] = $attribute_name;

        return $this;
    }

    /**
     * Gets attribute_min_value
     * @return int
     */
    public function getAttributeMinValue()
    {
        return $this->container['attribute_min_value'];
    }

    /**
     * Sets attribute_min_value
     * @param int $attribute_min_value The desired minimum value for the search attribute (inclusive).
     * @return $this
     */
    public function setAttributeMinValue($attribute_min_value)
    {
        $this->container['attribute_min_value'] = $attribute_min_value;

        return $this;
    }

    /**
     * Gets attribute_max_value
     * @return int
     */
    public function getAttributeMaxValue()
    {
        return $this->container['attribute_max_value'];
    }

    /**
     * Sets attribute_max_value
     * @param int $attribute_max_value The desired maximum value for the search attribute (inclusive).
     * @return $this
     */
    public function setAttributeMaxValue($attribute_max_value)
    {
        $this->container['attribute_max_value'] = $attribute_max_value;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\SquareConnect\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\SquareConnect\ObjectSerializer::sanitizeForSerialization($this));
    }
}


