<?php
/**
 * ErrorCategory
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect\Model;

/**
 * ErrorCategory Class Doc Comment
 *
 * @category    Class
 * @description Indicates which high-level category of error has occurred during a request to the Connect API.
 * @package     SquareConnect
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ErrorCategory
{
    /**
     * Possible values of this enum
     */
    const API_ERROR = 'API_ERROR';
    const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
    const INVALID_REQUEST_ERROR = 'INVALID_REQUEST_ERROR';
    const RATE_LIMIT_ERROR = 'RATE_LIMIT_ERROR';
    const PAYMENT_METHOD_ERROR = 'PAYMENT_METHOD_ERROR';
    const REFUND_ERROR = 'REFUND_ERROR';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::API_ERROR,
            self::AUTHENTICATION_ERROR,
            self::INVALID_REQUEST_ERROR,
            self::RATE_LIMIT_ERROR,
            self::PAYMENT_METHOD_ERROR,
            self::REFUND_ERROR,
        ];
    }
}


