<?php
/**
 * TenderType
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect\Model;

/**
 * TenderType Class Doc Comment
 *
 * @category    Class
 * @description Indicates a tender&#39;s type.
 * @package     SquareConnect
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TenderType
{
    /**
     * Possible values of this enum
     */
    const CARD = 'CARD';
    const CASH = 'CASH';
    const THIRD_PARTY_CARD = 'THIRD_PARTY_CARD';
    const SQUARE_GIFT_CARD = 'SQUARE_GIFT_CARD';
    const NO_SALE = 'NO_SALE';
    const OTHER = 'OTHER';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CARD,
            self::CASH,
            self::THIRD_PARTY_CARD,
            self::SQUARE_GIFT_CARD,
            self::NO_SALE,
            self::OTHER,
        ];
    }
}


