<?php
/**
 * V1Payment
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect\Model;

use \ArrayAccess;

/**
 * V1Payment Class Doc Comment
 *
 * @category    Class
 * @package     SquareConnect
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1Payment implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'v1Payment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'merchant_id' => 'string',
        'created_at' => 'string',
        'creator_id' => 'string',
        'device' => '\SquareConnect\Model\Device',
        'payment_url' => 'string',
        'receipt_url' => 'string',
        'inclusive_tax_money' => '\SquareConnect\Model\V1Money',
        'additive_tax_money' => '\SquareConnect\Model\V1Money',
        'tax_money' => '\SquareConnect\Model\V1Money',
        'tip_money' => '\SquareConnect\Model\V1Money',
        'discount_money' => '\SquareConnect\Model\V1Money',
        'total_collected_money' => '\SquareConnect\Model\V1Money',
        'processing_fee_money' => '\SquareConnect\Model\V1Money',
        'net_total_money' => '\SquareConnect\Model\V1Money',
        'refunded_money' => '\SquareConnect\Model\V1Money',
        'swedish_rounding_money' => '\SquareConnect\Model\V1Money',
        'gross_sales_money' => '\SquareConnect\Model\V1Money',
        'net_sales_money' => '\SquareConnect\Model\V1Money',
        'inclusive_tax' => '\SquareConnect\Model\V1PaymentTax[]',
        'additive_tax' => '\SquareConnect\Model\V1PaymentTax[]',
        'tender' => '\SquareConnect\Model\V1Tender[]',
        'refunds' => '\SquareConnect\Model\V1Refund[]',
        'itemizations' => '\SquareConnect\Model\V1PaymentItemization[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'merchant_id' => null,
        'created_at' => null,
        'creator_id' => null,
        'device' => null,
        'payment_url' => null,
        'receipt_url' => null,
        'inclusive_tax_money' => null,
        'additive_tax_money' => null,
        'tax_money' => null,
        'tip_money' => null,
        'discount_money' => null,
        'total_collected_money' => null,
        'processing_fee_money' => null,
        'net_total_money' => null,
        'refunded_money' => null,
        'swedish_rounding_money' => null,
        'gross_sales_money' => null,
        'net_sales_money' => null,
        'inclusive_tax' => null,
        'additive_tax' => null,
        'tender' => null,
        'refunds' => null,
        'itemizations' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'merchant_id' => 'merchant_id',
        'created_at' => 'created_at',
        'creator_id' => 'creator_id',
        'device' => 'device',
        'payment_url' => 'payment_url',
        'receipt_url' => 'receipt_url',
        'inclusive_tax_money' => 'inclusive_tax_money',
        'additive_tax_money' => 'additive_tax_money',
        'tax_money' => 'tax_money',
        'tip_money' => 'tip_money',
        'discount_money' => 'discount_money',
        'total_collected_money' => 'total_collected_money',
        'processing_fee_money' => 'processing_fee_money',
        'net_total_money' => 'net_total_money',
        'refunded_money' => 'refunded_money',
        'swedish_rounding_money' => 'swedish_rounding_money',
        'gross_sales_money' => 'gross_sales_money',
        'net_sales_money' => 'net_sales_money',
        'inclusive_tax' => 'inclusive_tax',
        'additive_tax' => 'additive_tax',
        'tender' => 'tender',
        'refunds' => 'refunds',
        'itemizations' => 'itemizations'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'merchant_id' => 'setMerchantId',
        'created_at' => 'setCreatedAt',
        'creator_id' => 'setCreatorId',
        'device' => 'setDevice',
        'payment_url' => 'setPaymentUrl',
        'receipt_url' => 'setReceiptUrl',
        'inclusive_tax_money' => 'setInclusiveTaxMoney',
        'additive_tax_money' => 'setAdditiveTaxMoney',
        'tax_money' => 'setTaxMoney',
        'tip_money' => 'setTipMoney',
        'discount_money' => 'setDiscountMoney',
        'total_collected_money' => 'setTotalCollectedMoney',
        'processing_fee_money' => 'setProcessingFeeMoney',
        'net_total_money' => 'setNetTotalMoney',
        'refunded_money' => 'setRefundedMoney',
        'swedish_rounding_money' => 'setSwedishRoundingMoney',
        'gross_sales_money' => 'setGrossSalesMoney',
        'net_sales_money' => 'setNetSalesMoney',
        'inclusive_tax' => 'setInclusiveTax',
        'additive_tax' => 'setAdditiveTax',
        'tender' => 'setTender',
        'refunds' => 'setRefunds',
        'itemizations' => 'setItemizations'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'merchant_id' => 'getMerchantId',
        'created_at' => 'getCreatedAt',
        'creator_id' => 'getCreatorId',
        'device' => 'getDevice',
        'payment_url' => 'getPaymentUrl',
        'receipt_url' => 'getReceiptUrl',
        'inclusive_tax_money' => 'getInclusiveTaxMoney',
        'additive_tax_money' => 'getAdditiveTaxMoney',
        'tax_money' => 'getTaxMoney',
        'tip_money' => 'getTipMoney',
        'discount_money' => 'getDiscountMoney',
        'total_collected_money' => 'getTotalCollectedMoney',
        'processing_fee_money' => 'getProcessingFeeMoney',
        'net_total_money' => 'getNetTotalMoney',
        'refunded_money' => 'getRefundedMoney',
        'swedish_rounding_money' => 'getSwedishRoundingMoney',
        'gross_sales_money' => 'getGrossSalesMoney',
        'net_sales_money' => 'getNetSalesMoney',
        'inclusive_tax' => 'getInclusiveTax',
        'additive_tax' => 'getAdditiveTax',
        'tender' => 'getTender',
        'refunds' => 'getRefunds',
        'itemizations' => 'getItemizations'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['merchant_id'] = isset($data['merchant_id']) ? $data['merchant_id'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['creator_id'] = isset($data['creator_id']) ? $data['creator_id'] : null;
        $this->container['device'] = isset($data['device']) ? $data['device'] : null;
        $this->container['payment_url'] = isset($data['payment_url']) ? $data['payment_url'] : null;
        $this->container['receipt_url'] = isset($data['receipt_url']) ? $data['receipt_url'] : null;
        $this->container['inclusive_tax_money'] = isset($data['inclusive_tax_money']) ? $data['inclusive_tax_money'] : null;
        $this->container['additive_tax_money'] = isset($data['additive_tax_money']) ? $data['additive_tax_money'] : null;
        $this->container['tax_money'] = isset($data['tax_money']) ? $data['tax_money'] : null;
        $this->container['tip_money'] = isset($data['tip_money']) ? $data['tip_money'] : null;
        $this->container['discount_money'] = isset($data['discount_money']) ? $data['discount_money'] : null;
        $this->container['total_collected_money'] = isset($data['total_collected_money']) ? $data['total_collected_money'] : null;
        $this->container['processing_fee_money'] = isset($data['processing_fee_money']) ? $data['processing_fee_money'] : null;
        $this->container['net_total_money'] = isset($data['net_total_money']) ? $data['net_total_money'] : null;
        $this->container['refunded_money'] = isset($data['refunded_money']) ? $data['refunded_money'] : null;
        $this->container['swedish_rounding_money'] = isset($data['swedish_rounding_money']) ? $data['swedish_rounding_money'] : null;
        $this->container['gross_sales_money'] = isset($data['gross_sales_money']) ? $data['gross_sales_money'] : null;
        $this->container['net_sales_money'] = isset($data['net_sales_money']) ? $data['net_sales_money'] : null;
        $this->container['inclusive_tax'] = isset($data['inclusive_tax']) ? $data['inclusive_tax'] : null;
        $this->container['additive_tax'] = isset($data['additive_tax']) ? $data['additive_tax'] : null;
        $this->container['tender'] = isset($data['tender']) ? $data['tender'] : null;
        $this->container['refunds'] = isset($data['refunds']) ? $data['refunds'] : null;
        $this->container['itemizations'] = isset($data['itemizations']) ? $data['itemizations'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param string $id The payment's unique identifier.
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets merchant_id
     * @return string
     */
    public function getMerchantId()
    {
        return $this->container['merchant_id'];
    }

    /**
     * Sets merchant_id
     * @param string $merchant_id The unique identifier of the merchant that took the payment.
     * @return $this
     */
    public function setMerchantId($merchant_id)
    {
        $this->container['merchant_id'] = $merchant_id;

        return $this;
    }

    /**
     * Gets created_at
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     * @param string $created_at The time when the payment was created, in ISO 8601 format.
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets creator_id
     * @return string
     */
    public function getCreatorId()
    {
        return $this->container['creator_id'];
    }

    /**
     * Sets creator_id
     * @param string $creator_id The unique identifier of the Square account that took the payment.
     * @return $this
     */
    public function setCreatorId($creator_id)
    {
        $this->container['creator_id'] = $creator_id;

        return $this;
    }

    /**
     * Gets device
     * @return \SquareConnect\Model\Device
     */
    public function getDevice()
    {
        return $this->container['device'];
    }

    /**
     * Sets device
     * @param \SquareConnect\Model\Device $device The device that took the payment.
     * @return $this
     */
    public function setDevice($device)
    {
        $this->container['device'] = $device;

        return $this;
    }

    /**
     * Gets payment_url
     * @return string
     */
    public function getPaymentUrl()
    {
        return $this->container['payment_url'];
    }

    /**
     * Sets payment_url
     * @param string $payment_url The URL of the payment's detail page in the merchant dashboard. The merchant must be signed in to the merchant dashboard to view this page.
     * @return $this
     */
    public function setPaymentUrl($payment_url)
    {
        $this->container['payment_url'] = $payment_url;

        return $this;
    }

    /**
     * Gets receipt_url
     * @return string
     */
    public function getReceiptUrl()
    {
        return $this->container['receipt_url'];
    }

    /**
     * Sets receipt_url
     * @param string $receipt_url The URL of the receipt for the payment. Note that for split tender payments, this URL corresponds to the receipt for the first tender listed in the payment's tender field. Each Tender object has its own receipt_url field you can use to get the other receipts associated with a split tender payment.
     * @return $this
     */
    public function setReceiptUrl($receipt_url)
    {
        $this->container['receipt_url'] = $receipt_url;

        return $this;
    }

    /**
     * Gets inclusive_tax_money
     * @return \SquareConnect\Model\V1Money
     */
    public function getInclusiveTaxMoney()
    {
        return $this->container['inclusive_tax_money'];
    }

    /**
     * Sets inclusive_tax_money
     * @param \SquareConnect\Model\V1Money $inclusive_tax_money The sum of all inclusive taxes associated with the payment.
     * @return $this
     */
    public function setInclusiveTaxMoney($inclusive_tax_money)
    {
        $this->container['inclusive_tax_money'] = $inclusive_tax_money;

        return $this;
    }

    /**
     * Gets additive_tax_money
     * @return \SquareConnect\Model\V1Money
     */
    public function getAdditiveTaxMoney()
    {
        return $this->container['additive_tax_money'];
    }

    /**
     * Sets additive_tax_money
     * @param \SquareConnect\Model\V1Money $additive_tax_money The sum of all additive taxes associated with the payment.
     * @return $this
     */
    public function setAdditiveTaxMoney($additive_tax_money)
    {
        $this->container['additive_tax_money'] = $additive_tax_money;

        return $this;
    }

    /**
     * Gets tax_money
     * @return \SquareConnect\Model\V1Money
     */
    public function getTaxMoney()
    {
        return $this->container['tax_money'];
    }

    /**
     * Sets tax_money
     * @param \SquareConnect\Model\V1Money $tax_money The total of all taxes applied to the payment. This is always the sum of inclusive_tax_money and additive_tax_money.
     * @return $this
     */
    public function setTaxMoney($tax_money)
    {
        $this->container['tax_money'] = $tax_money;

        return $this;
    }

    /**
     * Gets tip_money
     * @return \SquareConnect\Model\V1Money
     */
    public function getTipMoney()
    {
        return $this->container['tip_money'];
    }

    /**
     * Sets tip_money
     * @param \SquareConnect\Model\V1Money $tip_money The total of all tips applied to the payment.
     * @return $this
     */
    public function setTipMoney($tip_money)
    {
        $this->container['tip_money'] = $tip_money;

        return $this;
    }

    /**
     * Gets discount_money
     * @return \SquareConnect\Model\V1Money
     */
    public function getDiscountMoney()
    {
        return $this->container['discount_money'];
    }

    /**
     * Sets discount_money
     * @param \SquareConnect\Model\V1Money $discount_money The total of all discounts applied to the payment.
     * @return $this
     */
    public function setDiscountMoney($discount_money)
    {
        $this->container['discount_money'] = $discount_money;

        return $this;
    }

    /**
     * Gets total_collected_money
     * @return \SquareConnect\Model\V1Money
     */
    public function getTotalCollectedMoney()
    {
        return $this->container['total_collected_money'];
    }

    /**
     * Sets total_collected_money
     * @param \SquareConnect\Model\V1Money $total_collected_money The total of all discounts applied to the payment.
     * @return $this
     */
    public function setTotalCollectedMoney($total_collected_money)
    {
        $this->container['total_collected_money'] = $total_collected_money;

        return $this;
    }

    /**
     * Gets processing_fee_money
     * @return \SquareConnect\Model\V1Money
     */
    public function getProcessingFeeMoney()
    {
        return $this->container['processing_fee_money'];
    }

    /**
     * Sets processing_fee_money
     * @param \SquareConnect\Model\V1Money $processing_fee_money The total of all processing fees collected by Square for the payment.
     * @return $this
     */
    public function setProcessingFeeMoney($processing_fee_money)
    {
        $this->container['processing_fee_money'] = $processing_fee_money;

        return $this;
    }

    /**
     * Gets net_total_money
     * @return \SquareConnect\Model\V1Money
     */
    public function getNetTotalMoney()
    {
        return $this->container['net_total_money'];
    }

    /**
     * Sets net_total_money
     * @param \SquareConnect\Model\V1Money $net_total_money The amount to be deposited into the merchant's bank account for the payment.
     * @return $this
     */
    public function setNetTotalMoney($net_total_money)
    {
        $this->container['net_total_money'] = $net_total_money;

        return $this;
    }

    /**
     * Gets refunded_money
     * @return \SquareConnect\Model\V1Money
     */
    public function getRefundedMoney()
    {
        return $this->container['refunded_money'];
    }

    /**
     * Sets refunded_money
     * @param \SquareConnect\Model\V1Money $refunded_money The total of all refunds applied to the payment.
     * @return $this
     */
    public function setRefundedMoney($refunded_money)
    {
        $this->container['refunded_money'] = $refunded_money;

        return $this;
    }

    /**
     * Gets swedish_rounding_money
     * @return \SquareConnect\Model\V1Money
     */
    public function getSwedishRoundingMoney()
    {
        return $this->container['swedish_rounding_money'];
    }

    /**
     * Sets swedish_rounding_money
     * @param \SquareConnect\Model\V1Money $swedish_rounding_money
     * @return $this
     */
    public function setSwedishRoundingMoney($swedish_rounding_money)
    {
        $this->container['swedish_rounding_money'] = $swedish_rounding_money;

        return $this;
    }

    /**
     * Gets gross_sales_money
     * @return \SquareConnect\Model\V1Money
     */
    public function getGrossSalesMoney()
    {
        return $this->container['gross_sales_money'];
    }

    /**
     * Sets gross_sales_money
     * @param \SquareConnect\Model\V1Money $gross_sales_money
     * @return $this
     */
    public function setGrossSalesMoney($gross_sales_money)
    {
        $this->container['gross_sales_money'] = $gross_sales_money;

        return $this;
    }

    /**
     * Gets net_sales_money
     * @return \SquareConnect\Model\V1Money
     */
    public function getNetSalesMoney()
    {
        return $this->container['net_sales_money'];
    }

    /**
     * Sets net_sales_money
     * @param \SquareConnect\Model\V1Money $net_sales_money
     * @return $this
     */
    public function setNetSalesMoney($net_sales_money)
    {
        $this->container['net_sales_money'] = $net_sales_money;

        return $this;
    }

    /**
     * Gets inclusive_tax
     * @return \SquareConnect\Model\V1PaymentTax[]
     */
    public function getInclusiveTax()
    {
        return $this->container['inclusive_tax'];
    }

    /**
     * Sets inclusive_tax
     * @param \SquareConnect\Model\V1PaymentTax[] $inclusive_tax All of the inclusive taxes associated with the payment.
     * @return $this
     */
    public function setInclusiveTax($inclusive_tax)
    {
        $this->container['inclusive_tax'] = $inclusive_tax;

        return $this;
    }

    /**
     * Gets additive_tax
     * @return \SquareConnect\Model\V1PaymentTax[]
     */
    public function getAdditiveTax()
    {
        return $this->container['additive_tax'];
    }

    /**
     * Sets additive_tax
     * @param \SquareConnect\Model\V1PaymentTax[] $additive_tax All of the additive taxes associated with the payment.
     * @return $this
     */
    public function setAdditiveTax($additive_tax)
    {
        $this->container['additive_tax'] = $additive_tax;

        return $this;
    }

    /**
     * Gets tender
     * @return \SquareConnect\Model\V1Tender[]
     */
    public function getTender()
    {
        return $this->container['tender'];
    }

    /**
     * Sets tender
     * @param \SquareConnect\Model\V1Tender[] $tender All of the additive taxes associated with the payment.
     * @return $this
     */
    public function setTender($tender)
    {
        $this->container['tender'] = $tender;

        return $this;
    }

    /**
     * Gets refunds
     * @return \SquareConnect\Model\V1Refund[]
     */
    public function getRefunds()
    {
        return $this->container['refunds'];
    }

    /**
     * Sets refunds
     * @param \SquareConnect\Model\V1Refund[] $refunds All of the refunds applied to the payment.
     * @return $this
     */
    public function setRefunds($refunds)
    {
        $this->container['refunds'] = $refunds;

        return $this;
    }

    /**
     * Gets itemizations
     * @return \SquareConnect\Model\V1PaymentItemization[]
     */
    public function getItemizations()
    {
        return $this->container['itemizations'];
    }

    /**
     * Sets itemizations
     * @param \SquareConnect\Model\V1PaymentItemization[] $itemizations The items purchased in the payment.
     * @return $this
     */
    public function setItemizations($itemizations)
    {
        $this->container['itemizations'] = $itemizations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\SquareConnect\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\SquareConnect\ObjectSerializer::sanitizeForSerialization($this));
    }
}


